const ids = ["syncButton", "clearButton", "graceMinutes", "status", "statusDot", "tripCount", "tollCount", "matchedCount", "unmatchedCount", "matchedList", "unmatchedList", "lastSync", "assignmentForm", "vehicleId", "vehicleLabel", "identifierKind", "identifier", "validFrom", "validTo", "vehicleOptions", "assignmentList"];
const el = Object.fromEntries(ids.map((id) => [id, document.querySelector(`#${id}`)]));
let draftTimer;
function send(message) { return chrome.runtime.sendMessage(message).then((response) => { if (!response?.ok) throw new Error(response?.error || "Extension request failed."); return response; }); }
function setStatus(message, kind = "good") { el.status.textContent = message; el.status.className = `status${kind === "error" ? " error" : ""}`; el.statusDot.className = `status-dot ${kind}`; }
const money = (amount) => Number.isFinite(amount) ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(amount) : "Amount unavailable";
const time = (epoch, zone) => Number.isFinite(epoch) ? new Intl.DateTimeFormat("en-US", { timeZone: zone, dateStyle: "medium", timeStyle: "short" }).format(new Date(epoch)) : "Invalid date";
function card(title, detail, action) { const wrapper = document.createElement("article"); wrapper.className = "card"; const row = document.createElement("div"); row.className = "card-row"; const heading = document.createElement("strong"); heading.textContent = title; row.append(heading); if (action) row.append(action); const body = document.createElement("p"); body.textContent = detail; wrapper.append(row, body); return wrapper; }
function fill(container, cards, empty) { container.replaceChildren(...cards); container.classList.toggle("empty", !cards.length); if (!cards.length) container.textContent = empty; }
function draftValue() { return { vehicleId: el.vehicleId.value, label: el.vehicleLabel.value, kind: el.identifierKind.value, identifier: el.identifier.value, validFrom: el.validFrom.value, validTo: el.validTo.value }; }
function restoreDraft(draft = {}) { el.vehicleId.value = draft.vehicleId || ""; el.vehicleLabel.value = draft.label || ""; el.identifierKind.value = draft.kind || "tag"; el.identifier.value = draft.identifier || ""; el.validFrom.value = draft.validFrom || ""; el.validTo.value = draft.validTo || ""; }
function render(state, { restore = false } = {}) {
  const trips = state.sources?.turo?.records || [], tolls = state.sources?.ezpass?.records || [], result = state.reconciliation || { matched: [], ambiguous: [], unmatchedTolls: [] }, zone = state.settings?.timeZone || "America/New_York";
  el.tripCount.textContent = trips.length; el.tollCount.textContent = tolls.length; el.matchedCount.textContent = result.matched?.length || 0; el.unmatchedCount.textContent = (result.unmatchedTolls?.length || 0) + (result.ambiguous?.length || 0); el.graceMinutes.value = String(state.settings?.graceMinutes || 0); el.lastSync.textContent = state.lastSync ? `Synced ${new Date(state.lastSync).toLocaleString()}` : "Never synced";
  el.vehicleOptions.replaceChildren(...(state.fleet?.vehicles || []).map((vehicle) => { const option = document.createElement("option"); option.value = vehicle.vehicleId; option.label = vehicle.label || vehicle.vehicleId; return option; }));
  fill(el.assignmentList, (state.fleet?.assignments || []).map((assignment) => { const remove = document.createElement("button"); remove.type = "button"; remove.className = "danger"; remove.textContent = "Remove"; remove.dataset.assignmentId = assignment.id; return card(`${assignment.label || `Vehicle ${assignment.vehicleId}`} · ${assignment.kind} ${assignment.identifier}`, `${assignment.validFrom || "Any past date"} through ${assignment.validTo || "Any future date"} · Turo vehicle ${assignment.vehicleId}`, remove); }), "No dated assignments yet.");
  fill(el.matchedList, (result.matched || []).map(({ toll, trip, vehicleConfirmed, withinGrace }) => card(`${money(toll.amount)} · ${toll.plaza}`, `${time(toll.timestampMs, zone)} → vehicle ${trip.vehicleId}, trip ${trip.id}${vehicleConfirmed ? "" : " · Mapping required before invoicing"}${withinGrace ? " · Grace period" : ""}`)), "No matches yet.");
  const unmatched = (result.unmatchedTolls || []).map(({ toll, reason }) => card(`${money(toll.amount)} · ${toll.plaza}`, `${time(toll.timestampMs, zone)} · ${reason === "conflicting_vehicle_mapping" ? "Vehicle assignments conflict" : reason === "no_trip_in_time_range" ? "No trip in range" : "Record requires review"}`));
  for (const { toll, candidates } of result.ambiguous || []) unmatched.push(card(`${money(toll.amount)} · ${toll.plaza}`, `${time(toll.timestampMs, zone)} · overlaps ${candidates.length} trips`)); fill(el.unmatchedList, unmatched, "No unmatched tolls."); if (restore) restoreDraft(state.uiDrafts?.vehicleAssignment);
}
function scheduleDraftSave() { clearTimeout(draftTimer); draftTimer = setTimeout(() => send({ type: "SAVE_UI_DRAFT", draft: draftValue() }).catch((error) => setStatus(error.message, "error")), 250); }
for (const input of [el.vehicleId, el.vehicleLabel, el.identifierKind, el.identifier, el.validFrom, el.validTo]) input.addEventListener("input", scheduleDraftSave);
el.assignmentForm.addEventListener("submit", async (event) => { event.preventDefault(); clearTimeout(draftTimer); try { const { state } = await send({ type: "UPSERT_ASSIGNMENT", assignment: draftValue() }); render(state); restoreDraft({}); setStatus("Dated vehicle assignment saved; matches recalculated."); } catch (error) { setStatus(error.message, "error"); } });
el.assignmentList.addEventListener("click", async (event) => { const id = event.target?.dataset?.assignmentId; if (!id) return; try { const { state } = await send({ type: "DELETE_ASSIGNMENT", id }); render(state); setStatus("Assignment removed."); } catch (error) { setStatus(error.message, "error"); } });
el.graceMinutes.addEventListener("change", async () => { try { const { state } = await send({ type: "UPDATE_SETTINGS", settings: { graceMinutes: Number(el.graceMinutes.value) } }); render(state); setStatus("Grace period updated."); } catch (error) { setStatus(error.message, "error"); } });
el.syncButton.addEventListener("click", async () => { el.syncButton.disabled = true; setStatus("Waiting up to 20 seconds for both portals…", "busy"); try { const response = await send({ type: "RUN_SYNC" }); render(response.state); const errors = Object.entries(response.collection).filter(([, value]) => !value.ok).map(([key, value]) => `${key}: ${value.error}`); setStatus(response.synced ? "Portal records synced and fleet matches recalculated." : `Not refreshed; prior results retained. ${errors.join(" ")}`, response.synced ? "good" : "error"); } catch (error) { setStatus(error.message, "error"); } finally { el.syncButton.disabled = false; } });
el.clearButton.addEventListener("click", async () => { try { const { state } = await send({ type: "CLEAR_LOCAL_DATA" }); render(state, { restore: true }); setStatus("Local records, assignments, and drafts cleared."); } catch (error) { setStatus(error.message, "error"); } });
send({ type: "GET_STATE" }).then(({ state }) => { render(state, { restore: true }); setStatus("Ready."); }).catch((error) => setStatus(error.message, "error"));
